### ISSUE TITLE
[Bounty] Error in the calculation for Board Member Shares. 

### ISSUE THREAD

**Issue by BobbyMcWho** [ProjectWyvern/wyvern-ethereum#3]
As part of the Wyvern bounty program I submit:

In [Line 20](https://github.com/ProjectWyvern/wyvern-ethereum/blob/d7e3bb51a845cdcca9e7a260ea3ad0f8c774086c/contracts/WyvernDAO.sol#L20) of the WyvernDAO solidity contract, it states that the required shares to be a board member are 0.1% of the total supply. At the currently specified 200 * {decimals}, this is only .01% of the total supply to be a board member, which is a factor of ten less than the intended result.

**Comment by protinam** [comment]
Indeed, you are correct. Nice catch.

This could have been changed by the DAO later, but might have been inconvenient in the meantime, and is directly contrary to documentation. Rated as Medium; we'll pay you $250. Please provide an Ethereum address.

**Comment by protinam** [comment]
Fixed by 7efcaf150f2b05ecad531e9833048f8ba9f2a8e7 and no longer eligible as a bug submission.

**Comment by BobbyMcWho** [comment]
ETH address: 0x3D9317cC2e741794C8b53E175e2C1e28170F6e18

**Comment by protinam** [comment]
Paid: https://etherscan.io/tx/0x2f6fd14c3fb11be931929fea2b3455008baa38746f4485e305aabfbd42c0278d.
