### ISSUE TITLE
[Bounty] DAO newProposal beneficiary is not checked for account exsistance

### ISSUE THREAD

**Issue by bfmill253** [ProjectWyvern/wyvern-ethereum#6]
when a proposal is created the beneficiary is stored without checking on line 214 of DelegatedShareholderAssociation.sol.

```javascript
function newProposal(
        address beneficiary,
        uint weiAmount,
        bytes jobMetadataHash,
        bytes transactionBytecode
    )
        public
        onlyBoardMembers
        returns (uint proposalID)
    {
        proposalID = proposals.length++;
        Proposal storage p = proposals[proposalID];
        p.recipient = beneficiary;
...
```

when a proposal is executed the following is called on line 337 of DelegatedShareholderAssociation.sol.

```javascript
/* Execute the function. */
 require(p.recipient.call.value(p.amount)(transactionBytecode));
```

However this will return true whether p.recipient is valid or not.

https://solidity.readthedocs.io/en/develop/control-structures.html#error-handling-assert-require-revert-and-exceptions

> The low-level call, delegatecall and callcode will return success if the calling account is non-existent, as part of the design of EVM. Existence must be checked prior to calling if desired.

**Comment by protinam** [comment]
This is true; apart from being an annoyance if a proposal targeting a nonexistent account were created by accident, though, what issue could this lead to, or what part of the documentation did you think it contradicted?

**Comment by bfmill253** [comment]
From my understanding of the DAO I could see the following: 

Since each vote modifies the storage of the proposals array it will cost gas, if the beneficiary ends up being invalid then the gas price would double in order to recast votes for the proposal. This could also stall the proposal system if a rouge board member sends in multiple false proposals pointed to an invalid address (as all votes would need to be recast in order for the tokens to reach a valid address and serve their intended purpose).

If the beneficiary is checked in the newProposal call this could avoid any vote recast scenarios.

**Comment by protinam** [comment]
Yes, that's possible, but it should be easy for a proposal creator to check that an account exists prior to creating a proposal, or a tokenholder to check before spending gas to vote on the proposal.

Since there is a valid use case in sending to a nonexistent account - burning Ether - we don't plan to prevent that action from being taken by the DAO, but we'll note in documentation that proposal creators / voters should manually check that the beneficiary exists, presuming they don't intend to burn Ether.1

Rated Note; we'll pay $50. Please provide an Ethereum address.

**Comment by bfmill253** [comment]
Awesome. Thanks for the explanation

ETH Address: 0x2B34c70BE788350cA042b61dc40824c1e25278e7

**Comment by protinam** [comment]
Paid: https://etherscan.io/tx/0xdfa9989de879849189b013554143f3677c1247000c26e31b89e56dcbe0914c5f.

**Comment by protinam** [comment]
Additional documentation added in 644135714f8bf866da67395a8bc917eea64b434d.

Issue no longer eligible for bounty submission.
